# Generated by Django 4.0.6 on 2022-07-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name="Student's ID")),
                ('first_name', models.CharField(max_length=50, verbose_name="Student's First Name")),
                ('last_name', models.CharField(max_length=50, verbose_name="Student's Last Name")),
                ('is_active', models.BooleanField(default=True, verbose_name="Student's Activity Status")),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('student_email', models.CharField(max_length=255, unique=True, verbose_name="Student's e-mail")),
                ('group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
    ]
