# Generated by Django 4.0.6 on 2022-07-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name="Professor job position's ID")),
                ('title', models.CharField(max_length=20, verbose_name='Title of job')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorLinkPosition',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID of Professor and Position combination')),
                ('is_active', models.BooleanField(default=True, verbose_name="Combination's Activity Status")),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.jobposition', verbose_name='ID of position')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professor', verbose_name='ID of professor')),
            ],
        ),
    ]
