# Generated by Django 4.0.6 on 2022-07-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_jobposition_professorlinkposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professorlinkposition',
            old_name='position_id',
            new_name='position_fk',
        ),
        migrations.RenameField(
            model_name='professorlinkposition',
            old_name='professor_id',
            new_name='professor_fk',
        ),
    ]
