# Generated by Django 4.0.6 on 2022-07-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_rename_position_id_professorlinkposition_position_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorlinkposition',
            name='position_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.jobposition', verbose_name='ID of position'),
        ),
        migrations.AlterField(
            model_name='professorlinkposition',
            name='professor_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor', verbose_name='ID of professor'),
        ),
    ]
