# Generated by Django 4.0.6 on 2022-07-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='absence_period',
            field=models.DurationField(default=None, verbose_name='Missed Date Period'),
        ),
    ]
