# Generated by Django 4.0.6 on 2022-07-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_absence_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='absence_period',
        ),
    ]
