# Generated by Django 4.0.6 on 2022-07-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0003_alter_subjectlinkprofessor_professor_fk'),
        ('reports', '0002_report_subject_1to1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='student_1to1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student Reported'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subject_1to1',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Subject of Student Reported'),
        ),
    ]
