# Generated by Django 4.0.6 on 2022-07-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_grouplinkprofessorsubject_academ_year'),
        ('reports', '0003_alter_report_student_1to1_alter_report_subject_1to1'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='group_1to1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Group of Student'),
        ),
    ]
