# Generated by Django 4.0.6 on 2022-07-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_absence_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='period',
            field=models.DurationField(null=True, verbose_name='Dats of Absence'),
        ),
    ]
