# Generated by Django 4.0.6 on 2022-07-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subjectlinkprofessor_professor_fk'),
        ('reports', '0004_report_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='subject_skipped',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjectlinkprofessor'),
        ),
        migrations.AlterField(
            model_name='report',
            name='period',
            field=models.DurationField(null=True, verbose_name='Days of Absence'),
        ),
    ]
