# Generated by Django 4.0.6 on 2022-07-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_grouplinkprofessorsubject_academ_year'),
        ('reports', '0005_alter_report_group_1to1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='subject_1to1',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.grouplinkprofessorsubject', verbose_name='Subject of Student Reported'),
        ),
    ]
