# Generated by Django 4.0.6 on 2022-07-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subjectlinkprofessor_professor_fk'),
        ('reports', '0006_alter_report_subject_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='subject_skipped',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjectlinkprofessor'),
        ),
    ]
