# Generated by Django 4.0.6 on 2022-07-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_rename_position_id_professorlinkposition_position_fk_and_more'),
        ('subjects', '0003_alter_subjectlinkprofessor_professor_fk'),
        ('reports', '0006_alter_report_subject_1to1'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='professor_1to1',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='professors.professor', verbose_name='Professor of Student Reported'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subject_1to1',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Subject of Student Reported'),
        ),
    ]
