# Generated by Django 4.0.6 on 2022-07-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_professor_1to1_alter_report_subject_1to1'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='skipped_days',
            field=models.CharField(default='EXAMPLE: dd.mm.yyyy - dd.mm.yyyy', max_length=30, verbose_name='Days missed by student'),
        ),
    ]
