# Generated by Django 4.0.6 on 2022-07-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subjectlinkprofessor_professor_fk'),
        ('reports', '0007_alter_report_subject_skipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='subject_skipped',
        ),
        migrations.AddField(
            model_name='report',
            name='subject_missed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='report',
            name='period',
            field=models.DurationField(null=True, verbose_name='Skipped Period of Time'),
        ),
    ]
