# Generated by Django 4.0.6 on 2022-07-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subjectlinkprofessor_professor_fk'),
        ('reports', '0008_remove_report_subject_skipped_report_subject_missed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='subject_missed',
            field=models.OneToOneField(default='exit', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
            preserve_default=False,
        ),
    ]
