# Generated by Django 4.0.6 on 2022-07-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_skipped_days_alter_report_group_1to1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='document_pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Electronic Version of Document'),
        ),
    ]
