# Generated by Django 4.0.6 on 2022-07-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_report_skipped_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='skipped_days',
            field=models.CharField(default='dd.mm.yyyy - dd.mm.yyyy', max_length=120, verbose_name='Days missed by student'),
        ),
    ]
