# Generated by Django 4.0.6 on 2022-07-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_report_subject_missed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='period',
        ),
        migrations.RemoveField(
            model_name='report',
            name='subject_missed',
        ),
    ]
