# Generated by Django 4.0.6 on 2022-07-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_grouplinkprofessorsubject_academ_year'),
        ('professors', '0003_rename_position_id_professorlinkposition_position_fk_and_more'),
        ('students', '0001_initial'),
        ('subjects', '0004_alter_subjectlinkprofessor_professor_fk_and_more'),
        ('reports', '0010_alter_report_skipped_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='group_1to1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='report',
            name='professor_1to1',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor', verbose_name='Professor of Student Reported'),
        ),
        migrations.AlterField(
            model_name='report',
            name='student_1to1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='Student Reported'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subject_1to1',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject', verbose_name='Subject of Student Reported'),
        ),
    ]
