# Generated by Django 4.0.6 on 2022-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name="Group's ID")),
                ('group_name', models.CharField(max_length=50, unique=True, verbose_name="Group's Name")),
                ('is_active', models.BooleanField(default=True, verbose_name="Group's Activity Status")),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
        ),
    ]
