# Generated by Django 4.0.6 on 2022-07-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subjectlinkprofessor'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLinkProfessorSubject',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID of Group and Professor+Subject combination')),
                ('term_count', models.IntegerField(default=1, verbose_name="The term's number")),
                ('academ_year', models.CharField(default='FORMAT: yyyy - yyyy', max_length=30, unique=True, verbose_name='ACADEM YEAR')),
                ('is_active', models.BooleanField(default=True, verbose_name="Combination's Activity Status")),
                ('group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='ID of Group')),
                ('prof_subj_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subjectlinkprofessor', verbose_name='ID of Subject and Professor combination')),
            ],
        ),
    ]
