# Generated by Django 4.0.6 on 2022-07-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_grouplinkprofessorsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplinkprofessorsubject',
            name='academ_year',
            field=models.CharField(default='FORMAT: yyyy - yyyy', max_length=30, verbose_name='ACADEM YEAR'),
        ),
    ]
