# Generated by Django 4.0.6 on 2022-07-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_subjectlinkprofessor_professor_fk_and_more'),
        ('groups', '0003_alter_grouplinkprofessorsubject_academ_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplinkprofessorsubject',
            name='group_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group', verbose_name='ID of Group'),
        ),
        migrations.AlterField(
            model_name='grouplinkprofessorsubject',
            name='prof_subj_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subjectlinkprofessor', verbose_name='ID of Subject and Professor combination'),
        ),
    ]
