# Generated by Django 4.0.6 on 2022-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name="Subject's ID")),
                ('title', models.CharField(max_length=120, unique=True, verbose_name="Subject's Title")),
                ('is_retake', models.BooleanField(default=False, verbose_name='Retaken status')),
            ],
        ),
    ]
