# Generated by Django 4.0.6 on 2022-07-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_jobposition_professorlinkposition'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectLinkProfessor',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID of Subject and Professor combination')),
                ('professor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professor', verbose_name='Professors of this Subject')),
                ('subject_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Subjects of this Professor')),
            ],
        ),
    ]
