# Generated by Django 4.0.6 on 2022-07-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_rename_position_id_professorlinkposition_position_fk_and_more'),
        ('subjects', '0002_subjectlinkprofessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectlinkprofessor',
            name='professor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professorlinkposition', verbose_name='Professors of this Subject'),
        ),
    ]
