# Generated by Django 4.0.6 on 2022-07-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_rename_position_id_professorlinkposition_position_fk_and_more'),
        ('subjects', '0003_alter_subjectlinkprofessor_professor_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectlinkprofessor',
            name='professor_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professorlinkposition', verbose_name='Professors of this Subject'),
        ),
        migrations.AlterField(
            model_name='subjectlinkprofessor',
            name='subject_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject', verbose_name='Subjects of this Professor'),
        ),
    ]
